---
title: Shopping Mates
timezone: Europe/Berlin
author: Aleksej Dix
description: happy shopping with siroop shopping mates
twitter:
  username: Aleksej_Dix
collections:
  mates:
    title: Mates
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
    header image:
    excerpt:
    is featured: false
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: mates
    type: mates
  values:
    layout: page
    image:
    twitter_username:
email: privat@aleksejdix.com
baseurl:
url: http://aleksejdix.github.io/shopping-mates
markdown: kramdown
gems:
- jekyll-sitemap
- jekyll-seo-tag
permalink: pretty
