---
title: Your awesome title
timezone: UTC
collections:
  mates:
    title: Mates
    output: true
    permalink: mates
  post:
    title: Posts
    output: true
    permalink: post
    image: "/uploads/0-02-01-a41b6c59e7a59feddeb4d8d227a4c80a63b9c3bf84912d13448d9de6c8762b79_full.jpg"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@domain.com
description: |
  Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
baseurl: ''
url: http://yourdomain.com
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
