---
title: Shopping Mates
timezone: Europe/Berlin
collections:
  mates:
    title: Mates
    output: true
    permalink: mates
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: privat@aleksejdix.com
description: happy shopping with siroop shopping mates
baseurl: 
url: http://aleksejdix.com/shopping-mates/
twitter_username: jekyllrb
github_username: AleksejDix
markdown: kramdown
