---
title: Shopping Mates
timezone: Europe/Berlin
# Permalinks
permalink: pretty
collections:
  topics:
    title: Topics
    output: true
    permalink: /blog/:title/
  mates:
    title: Mates
    output: true
    permalink: /mates/:title/
  posts:
    title: Posts
    output: true
    permalink: /blog/:title/
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    header image:
    topic:
    mate:
- scope:
    path: ''
    type: mates
  values:
    layout: mate
    image:
    twitter_username:
- scope:
    path: ''
    type: topics
  values:
    layout: topic
    image:

author: Aleksej Dix
description: happy shopping with siroop shopping mates
email: privat@aleksejdix.com
baseurl: "/shopping-mates"
url: https://aleksejdix.com
markdown: kramdown
kramdown:
  input: GFM
include:
- ".htaccess"
exclude:
- _config.yml
- .gitignore"
- node_modules
- start.sh
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
keep_files:
- ".git"
encoding: utf-8
readingspeed: 200
# blog archive at /blog
paginate: 5
paginate_path: "blog/page/:num"
gems:
- jekyll-sitemap
- jekyll-seo-tag
google_analytics_ua:
# sass:
#   style: compressed
