---
title: Shopping Mates
timezone: Europe/Berlin
collections:
  mates:
    title: Mates
    output: true
    permalink: "/:collection/:path"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: mates
    type: mates
  values:
    layout: page
    twitter_username: 
email: privat@aleksejdix.com
description: happy shopping with siroop shopping mates
baseurl: 
url: 
markdown: kramdown
gems:
- jekyll-sitemap
permalink: pretty
