---
title: Shopping Mates
timezone: Europe/Berlin
collections:
  categories:
    title: Categories
    output: true
  mates:
    title: Mates
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    header image:
    categories: hidden
    mate: Aleksej
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: mates
  values:
    layout: mate
    image:
    twitter_username:
paginate: 2
paginate_path: "/posts/page:num/"
author: Aleksej Dix
description: happy shopping with siroop shopping mates
twitter:
  username: Aleksej_Dix
email: privat@aleksejdix.com
baseurl: "/shopping-mates"
url: https://aleksejdix.com
markdown: kramdown
gems:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-paginate
permalink: pretty
