---
title: Shopping Mates
timezone: Europe/Berlin
collections:
  mates:
    title: Mates
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
    header image: 
    excerpt: 
    is featured: false
    mate: Aleksej
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: mates
  values:
    layout: mate
    image: 
    twitter_username: 
author: Aleksej Dix
description: This must be change
twitter:
  username: Aleksej_Dix
email: privat@aleksejdix.com
baseurl: "/shopping-mates"
url: https://aleksejdix.com
markdown: kramdown
gems:
- jekyll-sitemap
- jekyll-seo-tag
permalink: pretty
