---
title: Shopping Mates
timezone: Europe/Berlin
collections:
  mates:
    title: Mates
    output: true
    permalink: "/:collection/:path"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: privat@aleksejdix.com
description: happy shopping with siroop shopping mates
baseurl:
url: http://127.0.0.1:4000
markdown: kramdown
gems:
- jekyll-sitemap
