---
title: Shopping Mates
timezone: Europe/Berlin
collections:
  categories:
    title: Categories
    output: true
  mates:
    title: Mates
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    header image:
    mate: Aleksej
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: mates
  values:
    layout: mate
    image:
    twitter_username:
author: Aleksej Dix
description: happy shopping with siroop shopping mates
email: privat@aleksejdix.com
baseurl: "/shopping-mates"
url: https://aleksejdix.com
markdown: kramdown
include: ["_pages"]
gems:
- jekyll-sitemap
- jekyll-seo-tag
permalink: pretty
